### ISSUE TITLE
Possible issue with max sendto amount

### ISSUE THREAD

**Issue by missilefish** [fedoracoin/fedoracoin#2]
I have a user on my pool with a valid address, he has a large amount of coin accumulated, over 800 million. I am getting RPC errors from the wallet trying to send them. Is there a maximum size to send at a single time?

**Comment by RBech** [comment]
Maximum amount you can send at once is 2.5 billion :)

**Comment by missilefish** [comment]
Negative. please read what I wrote. This issue is long gone, but the coind has an issue. I am closing this anyway, but it is a deeper issue the archives can refer to some date from now.

**Comment by RBech** [comment]
Arh, yeah I'm speaking in terms of the latest version (0.55), in this version the max amount got raised. But if the issue persists feel free to swing by irc and explain in further detail
