### ISSUE TITLE
Not a single confirm in 30 minutes???? WTF!!!

### ISSUE THREAD

**Issue by missilefish** [fedoracoin/fedoracoin#5]
I need to migrate the balance from the 1st central wallet to a new one, i can't get any network confirmations to go!!! I have the pool down due to this. Did this coin die from the update????

I have a billion more coins to move over!!!!

fedoracoind listsinceblock
{
    "transactions" : [
        {
            "account" : "",
            "address" : "EbuChvqUuUba8vMBWYS4CsXTvdHMPQDhmH",
            "category" : "receive",
            "amount" : 1000000.00000000,
            "confirmations" : 0,
            "txid" : "941f048c78820246bc3e80bda1318c3fdeb6778f21862df351b9c2e4d9ede100",
            "time" : 1391631831,
            "timereceived" : 1391631831
        }
    ],
    "lastblock" : "8adaef31126446b9479c05ffd3d46fd4b22e83ada6acc3f26afd379ab73c618a"
}

**Comment by missilefish** [comment]
fedoracoind getinfo
{
    "version" : 1000506,
    "protocolversion" : 60003,
    "walletversion" : 60000,
    "balance" : 0.00000000,
    "blocks" : 50658,
    "timeoffset" : 107,
    "connections" : 8,
    "proxy" : "",
    "difficulty" : 109.04893141,
    "testnet" : false,
    "keypoololdest" : 1391621858,
    "keypoolsize" : 102,
    "paytxfee" : 0.00000000,
    "mininput" : 0.00001000,
    "errors" : ""
}

**Comment by missilefish** [comment]
Hello? Earth to fedoracoin pool operators, has no one other than me noticed the complete failure on the network? I've been watching other pools and the public block report on their MPoS installs are unchanged in every case!

**Comment by invisibel** [comment]
Thanks to the multipools and coin switchers the difficulty's spiked to a high difficulty while they've switched coins because of it, leaving the core miners to mine with a noticeably higher difficulty.
Since this has continued for several days other miners have left and after the difficulty spikes up there's hardly enough hash power to find blocks, which slows block times (and transaction confirms) to 1 every hour or so.
After block 51000 the new difficulty fix will kick in and the network should be able to adjust for multipools better giving us proper block times.

**Comment by missilefish** [comment]
This is not an answer, I am talking about SIMPLE NETWORK CONFIRMATIONS from network peers. You had a brief period of network confirmations but then it all died again. 

I have been running a pool on your coin since the very early days, I am notnull.

**Comment by missilefish** [comment]
i'm talking about transferring coin, the network is seriously that weak?

**Comment by icanprogram** [comment]
[Yes](http://fedoracha.in/chain/FedoraCoin)

**Comment by missilefish** [comment]
I'm so relieved that bitcoin, litecoin, and any other network doesn't have the same problem. Oh and i have some of those in the last 4 hours. This is not MULTIPOOL related FUD.

**Comment by missilefish** [comment]
<a href="http://fedoracha.in/block/c3779be86eb5ae8afbf7162e20540f5999fac4fed6893d5a5ff9c484e0f68a86">No</a>
